controlefinanceiro/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    #URL padrão
    path('', include('website.urls', namespace='website')),

    path('admin/', admin.site.urls),
]

website/urls.py
from django.urls import path
from website.views import IndexTemplateView, ContasPagarListView, ContasPagarUpdateView, ContasPagarDeleteView, ContasPagarCreateView
from website.views import ClassificacaoPagarCreateView, ClassificacaoPagarListView, ClassificacaoPagarUpdateView, ClassificacaoPagarDeleteView
from website.views import ContasReceberCreateView, ContasReceberDeleteView, ContasReceberListView, ContasReceberUpdateView
from website.views import FormasPagamentoListView, FormasPagamentoCreateView, FormasPagamentoUpdateView, FormasPagamentoDeleteView
from website.views import FluxoListView

app_name = 'website'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name="index"),
    #Contas a pagar
    path('contaspagar/cadastrar/', ContasPagarCreateView.as_view(), name = "cria_contas_pagar"),
    path('contaspagar/', ContasPagarListView.as_view(), name="lista_contas_pagar"),
    path('contaspagar/<pk>', ContasPagarUpdateView.as_view(), name="atualiza_contas_pagar"),
    path('contaspagar/excluir/<pk>', ContasPagarDeleteView.as_view(), name="exclui_contas_pagar"),

    #Contas a receber
    path('contasreceber/cadastrar/', ContasReceberCreateView.as_view(), name = "cria_contas_receber"),
    path('contasreceber/', ContasReceberListView.as_view(), name="lista_contas_receber"),
    path('contasreceber/<pk>', ContasReceberUpdateView.as_view(), name="atualiza_contas_receber"),
    path('contasreceber/excluir/<pk>', ContasReceberDeleteView.as_view(), name="exclui_contas_receber"),
        
    #Classificação de contas a pagar
    path('classificacaopagar/cadastrar/', ClassificacaoPagarCreateView.as_view(), name = "cria_classificacao_pagar"),
    path('classificacaopagar/', ClassificacaoPagarListView.as_view(), name="lista_classificacao_pagar"),
    path('classificacaopagar/<pk>', ClassificacaoPagarUpdateView.as_view(), name="atualiza_classificacao_pagar"),
    path('classificacaopagar/excluir/<pk>', ClassificacaoPagarDeleteView.as_view(), name="exclui_classificacao_pagar"),

    #Formas de pagamento
    path('formaspagamento/cadastrar/', FormasPagamentoCreateView.as_view(), name = "cria_formas_pagamento"),
    path('formaspagamento/', FormasPagamentoListView.as_view(), name="lista_formas_pagamento"),
    path('formaspagamento/<pk>', FormasPagamentoUpdateView.as_view(), name="atualiza_formas_pagamento"),
    path('formaspagamento/excluir/<pk>', FormasPagamentoDeleteView.as_view(), name="exclui_formas_pagamento"),

    #FLUXOS
    path('fluxo/', FluxoListView.as_view(), name = "fluxo"),   
    path('fluxomensal/', FluxoListView.as_view(), name = "fluxomensal")
]

website/forms.py
from django import forms
from bootstrap_datepicker_plus import DateTimePickerInput
from controlefinanceiro.models import ContasPagar, ContasReceber, ClassificacaoPagar, FormaPagamento

class InsereContasPagarForm(forms.ModelForm):         

    class Meta:
        model = ContasPagar

        fields = [           
            'data_vencimento',
            'data_pagamento',
            'valor',
            'descricao',
            'situacao',            
            'classificacoes',
            'formaspagamento'
        ]

        labels = {
            'data_vencimento': 'Data de Vencimento',
            'data_pagamento': 'Data de Pagamento ',
            'valor': 'Valor',
            'descricao': 'Descrição',
            'situacao': 'Situação',
            'classificacoes': 'Classificação',
            'formaspagamento': 'Forma de Pagamento'
        }

        widgets = {            
            'data_vencimento': DateTimePickerInput(format='%Y-%m-%d'), # specify date-frmat
            'data_pagamento': DateTimePickerInput(format='%Y-%m-%d'), # specify date-frmat
        }

class InsereContasReceberForm(forms.ModelForm):                        
    class Meta:
        model = ContasReceber
        fields = [
            'data_expectativa',
            'data_recebimento',
            'valor',
            'descricao',
            'situacao',
            'classificacoes',
            'formaspagamento' 
        ]
        labels = {
            'data_expectativa': 'Data de Expectativa de Recebimento',
            'data_recebimento': 'Data de Recebimento ',
            'valor': 'Valor',
            'descricao': 'Descrição',
            'situacao': 'Situação',
            'classificacoes': 'Classificação',
            'formaspagamento': 'Forma de Pagamento'
        }

        widgets = {            
            'data_expectativa': DateTimePickerInput(format='%Y-%m-%d'), # specify date-frmat
            'data_recebimento': DateTimePickerInput(format='%Y-%m-%d'), # specify date-frmat
        }

class InsereClassificaoPagarForm(forms.ModelForm):
    class Meta:
        model = ClassificacaoPagar
        fields = [
            'descricao',
            'tipo'
        ]

class InsereFormasPagamento(forms.ModelForm):
    class Meta:
        model = FormaPagamento
        fields = [
            'descricao'
        ]        

website/views.py
from django.views.generic import TemplateView, ListView, UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy
from django.db.models.functions import Cast
from django.db.models import Sum
from controlefinanceiro.models import ContasPagar, ContasReceber, ClassificacaoPagar, FormaPagamento
from website.forms import InsereContasPagarForm, InsereContasReceberForm, InsereClassificaoPagarForm, InsereFormasPagamento

# Create your views here.
class IndexTemplateView(TemplateView):
    template_name = "website/index.html"

#CONTAS A PAGAR ---------------------------------------------------------------    

class ContasPagarCreateView(CreateView):
    template_name = "website/contaspagar/criacontaspagar.html"
    model = ContasPagar
    form_class = InsereContasPagarForm
    success_url = reverse_lazy("website:lista_contas_pagar")

class ContasPagarListView(ListView):
    template_name = "website/contaspagar/listacontaspagar.html"
    model = ContasPagar    
    context_object_name = "contaspagar"
    
class ContasPagarUpdateView(UpdateView):
    template_name = "website/contaspagar/atualizacontaspagar.html"    
    model = ContasPagar
    fields = '__all__'
    context_objetc_name = "contaspagar"
    success_url = reverse_lazy("website:lista_contas_pagar")

class ContasPagarDeleteView(DeleteView):
    template_name = "website/contaspagar/excluicontaspagar.html"
    model = ContasPagar
    context_objetc_name = "contaspagar"
    success_url = reverse_lazy("website:lista_contas_pagar")

#CONTAS A RECEBER ---------------------------------------------------------------    

class ContasReceberCreateView(CreateView):
    template_name = "website/contasreceber/criacontasreceber.html"
    model = ContasReceber
    form_class = InsereContasReceberForm
    success_url = reverse_lazy("website:lista_contas_receber")

class ContasReceberListView(ListView):
    template_name = "website/contasreceber/listacontasreceber.html"
    model = ContasReceber
    context_object_name = "contasreceber"

class ContasReceberUpdateView(UpdateView):
    template_name = "website/contasreceber/atualizacontasreceber.html"    
    model = ContasReceber
    fields = '__all__'
    context_objetc_name = "contasreceber"
    success_url = reverse_lazy("website:lista_contas_receber")

class ContasReceberDeleteView(DeleteView):
    template_name = "website/contasreceber/excluicontasreceber.html"
    model = ContasReceber
    context_objetc_name = "contasreceber"
    success_url = reverse_lazy("website:lista_contas_receber")


#CLASSIFICAÇÃO DE CONTAS ---------------------------------------------------------------    

class ClassificacaoPagarCreateView(CreateView):
    template_name = "website/classificacaopagar/criaclassificacaopagar.html"
    model = ClassificacaoPagar
    form_class = InsereClassificaoPagarForm
    success_url = reverse_lazy("website:lista_classificacao_pagar")


class ClassificacaoPagarListView(ListView):
    template_name = "website/classificacaopagar/listaclassificacaopagar.html"
    model = ClassificacaoPagar
    context_object_name = "classificacaopagar"  
    
class ClassificacaoPagarUpdateView(UpdateView):
    template_name = "website/classificacaopagar/atualizaclassificacaopagar.html"    
    model = ClassificacaoPagar
    fields = '__all__'
    context_objetc_name = "classificacaopagar"
    success_url = reverse_lazy("website:lista_classificacao_pagar")

class ClassificacaoPagarDeleteView(DeleteView):
    template_name = "website/classificacaopagar/excluiclassificacaopagar.html"
    model = ClassificacaoPagar
    context_objetc_name = "classificacaopagar"
    success_url = reverse_lazy("website:lista_classificacao_pagar")   


#FORMAS DE PAGAMENTOS ---------------------------------------------------------------    
class FormasPagamentoListView(ListView):
    template_name = "website/formapagamento/listaformaspagamento.html"
    model = FormaPagamento
    context_object_name = "formapagamento"  

class FormasPagamentoCreateView(CreateView):
    template_name = "website/formapagamento/criaformaspagamento.html"
    model = FormaPagamento
    form_class = InsereFormasPagamento
    success_url = reverse_lazy("website:lista_formas_pagamento")

class FormasPagamentoUpdateView(UpdateView):
    template_name = "website/formapagamento/atualizaformaspagamento.html"    
    model = FormaPagamento
    fields = '__all__'
    context_objetc_name = "formapagamento"
    success_url = reverse_lazy("website:lista_formas_pagamento")

class FormasPagamentoDeleteView(DeleteView):
    template_name = "website/formapagamento/excluiformaspagamento.html"
    model = FormaPagamento
    context_objetc_name = "formapagamento"
    success_url = reverse_lazy("website:lista_formas_pagamento")   


class FluxoListView(ListView):
    template_name= "website/fluxo.html"

    context_object_name = "fluxo"       

    def get_queryset(self):
        return ContasPagar.objetos.order_by("data_vencimento").values('descricao', 'data_vencimento', 'data_pagamento', 'valor',
         'situacao')

    def get_context_data(self, **kwargs):
        context = super(FluxoListView, self).get_context_data(**kwargs  )
        context ['fluxoreceber']= {
            'fluxoreceber': ContasReceber.objetos.order_by("data_expectativa").values('descricao', 'data_expectativa',
                'data_recebimento', 'valor', 'situacao'), 
            'total_pagar': ContasPagar.objetos.all().filter(situacao = 'Pago').aggregate(Sum('valor')),
            'total_receber': ContasReceber.objetos.all().filter(situacao = 'Recebido').aggregate(Sum('valor'))
        }
        return context

    
    

website/templates/website/fluxo.html
{% extends "website/_layouts/base.html" %}

{% block title %}Fluxo{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Fluxo</h5>

          {% if fluxo|length > 0 %}
            <p class="card-text">
              Lista de <code>Contas a Pagar</code> cadastradas.
            </p>

            <table class="table">
              <thead class="thead-dark">
              <tr>
                <th scope="col"></th>
                <th scope="col">Descrição</th>
                <th scope="col">Data de Vencimento</th>
                <th scope="col">Data de Pagamento</th>
                <th scope="col">Valor</th>
                <th scope="col">Situacao</th>                
              </tr>
              </thead>
              <tbody>
              
              {% for fluxo in fluxo %}
                <tr>
                  <th scope="row">{{ fluxo.descricao }}</th>
                  <td>{{ fluxo.data_vencimento }}</td>
                  <td>{{ fluxo.data_pagamento }}</td>
                  <td>{{ fluxo.valor }}</td>
                  <td>{{ fluxo.situacao }}</td>                       
                </tr>               
              {% endfor %}

              {{ fluxo.total_pagar }}
              
              {% for fluxoreceber in fluxoreceber %}
              <tr>
                <th scope="row">{{ fluxoreceber.descricao }}</th>
                <td>{{ fluxoreceber.data_expectativa }}</td>
                <td>{{ fluxoreceber.data_recebimento }}</td>
                <td>{{ fluxoreceber.valor }}</td>
                <td>{{ fluxoreceber.situacao }}</td>                       
              </tr>              
            {% endfor %}
            {{ fluxo.total_receber }}
              </tbody>
            </table>
            
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhuma <code>conta</code> cadastrada ainda.</h5>
          </div>
        {% endif %}
          <hr />
  
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/fluxomensal.html
{% extends "website/_layouts/base.html" %}

{% load mathfilters %}

{% block title %}Fluxo{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Fluxo</h5>

          {% if fluxo|length > 0 %}
            <p class="card-text">
              Fluxo <code>Por Mês</code>.
            </p>

            <table class="table">
              <thead class="thead-dark">
              <tr>                
                <th scope="col">Descrição</th>
                <th scope="col">Data de Vencimento</th>
                <th scope="col">Data de Pagamento</th>
                <th scope="col">Valor</th>
                <th scope="col">Situacao</th>                
              </tr>
              </thead>
              <tbody>
              
              {% for fluxo in fluxo %}


                <tr>
                  <th scope="row">{{ fluxo.descricao }}</th>
                  <td>{{ fluxo.data_vencimento|date:'d/m/Y' }}</td>
                  <td>{{ fluxo.data_pagamento|date:'d/m/Y' }}</td>
                  <td>{{ fluxo.valor }}</td>
                  <td>{{ fluxo.situacao }}</td>                       
                </tr>               
              {% endfor %}             
              </tbody>
            </table>

            <p>Recebido: {{fluxoreceber.total_receber.valor__sum }}</p>
 
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  
                  <th scope="col">Descrição</th>
                  <th scope="col">Data de Vencimento</th>
                  <th scope="col">Data de Pagamento</th>
                  <th scope="col">Valor</th>
                  <th scope="col">Situacao</th>                
                </tr>
              </thead>              
              <tbody>
                {% for fluxoreceber in fluxoreceber.fluxoreceber %}
                <tr>
                  <th scope="row">{{ fluxoreceber.descricao }}</th>
                  <td>{{ fluxoreceber.data_expectativa|date:'d/m/Y' }}</td>
                  <td>{{ fluxoreceber.data_recebimento|date:'d/m/Y' }}</td>
                  <td>{{ fluxoreceber.valor }}</td>
                  <td>{{ fluxoreceber.situacao }}</td>                       
                </tr>              
                {% endfor %}
              </tbody>
              
            </table>

            <div>
              <p> Saldo: {{fluxoreceber.total_receber.valor__sum | sub:fluxoreceber.total_pagar.valor__sum}}</p>
            </div>
            
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhuma <code>conta</code> cadastrada ainda.</h5>
          </div>
        {% endif %}
          <hr />
  
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/index.html
{% extends "website/_layouts/base.html" %}

{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar uma conta a pagar</h5>
          <p class="card-text">
            Cadastre aqui uma nova <code>Conta</code>.
          </p>
          <a href="{% url 'website:cria_contas_pagar' %}"
             class="btn btn-primary">
            Nova Conta a Pagar
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Contas a Pagar</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Contas</code> cadastradas.
          </p>
          <a href="{% url 'website:lista_contas_pagar' %}"
             class="btn btn-primary">
            Vá para Lista
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar uma classificação de conta a pagar</h5>
          <p class="card-text">
            Cadastre aqui uma nova <code>Classificação</code>.
          </p>
          <a href="{% url 'website:cria_classificacao_pagar' %}"
             class="btn btn-primary">
            Nova Conta a Pagar
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Classificação de Contas a Pagar</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Classificação</code> cadastradas.
          </p>
          <a href="{% url 'website:lista_classificacao_pagar' %}"
             class="btn btn-primary">
            Vá para Lista
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar uma conta a receber</h5>
          <p class="card-text">
            Cadastre aqui uma nova <code>Conta</code>.
          </p>
          <a href="{% url 'website:cria_contas_receber' %}"
             class="btn btn-primary">
            Nova Conta a Pagar
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Contas a Receber</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Contas</code> cadastradas.
          </p>
          <a href="{% url 'website:lista_contas_receber' %}"
             class="btn btn-primary">
            Vá para Lista
          </a>
        </div>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar uma forma de pagamento</h5>
          <p class="card-text">
            Cadastre aqui uma nova <code>forma de pagamento</code>.
          </p>
          <a href="{% url 'website:cria_formas_pagamento' %}"
             class="btn btn-primary">
            Nova Forma de Pagamento
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Formas de Pagamento</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Formas de Pagamento</code> cadastradas.
          </p>
          <a href="{% url 'website:lista_formas_pagamento' %}"
             class="btn btn-primary">
            Vá para Lista
          </a>
        </div>
      </div>
    </div>
  </div>

  
</div>
{% endblock %}