controlefinanceiro/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    #URL padrão
    path('', include('website.urls', namespace='website')),

    path('admin/', admin.site.urls),
]

website/urls.py
from django.urls import path
from website.views import IndexTemplateView, ContasPagarListView, ContasPagarUpdateView, ContasPagarDeleteView, ContasPagarCreateView
from website.views import ClassificacaoPagarCreateView, ClassificacaoPagarListView, ClassificacaoPagarUpdateView, ClassificacaoPagarDeleteView
from website.views import ContasReceberCreateView, ContasReceberDeleteView, ContasReceberListView, ContasReceberUpdateView
from website.views import FormasPagamentoListView, FormasPagamentoCreateView, FormasPagamentoUpdateView, FormasPagamentoDeleteView
from website.views import FluxoListView

app_name = 'website'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name="index"),
    #Contas a pagar
    path('contaspagar/cadastrar/', ContasPagarCreateView.as_view(), name = "cria_contas_pagar"),
    path('contaspagar/', ContasPagarListView.as_view(), name="lista_contas_pagar"),
    path('contaspagar/<pk>', ContasPagarUpdateView.as_view(), name="atualiza_contas_pagar"),
    path('contaspagar/excluir/<pk>', ContasPagarDeleteView.as_view(), name="exclui_contas_pagar"),

    #Contas a receber
    path('contasreceber/cadastrar/', ContasReceberCreateView.as_view(), name = "cria_contas_receber"),
    path('contasreceber/', ContasReceberListView.as_view(), name="lista_contas_receber"),
    path('contasreceber/<pk>', ContasReceberUpdateView.as_view(), name="atualiza_contas_receber"),
    path('contasreceber/excluir/<pk>', ContasReceberDeleteView.as_view(), name="exclui_contas_receber"),
        
    #Classificação de contas a pagar
    path('classificacaopagar/cadastrar/', ClassificacaoPagarCreateView.as_view(), name = "cria_classificacao_pagar"),
    path('classificacaopagar/', ClassificacaoPagarListView.as_view(), name="lista_classificacao_pagar"),
    path('classificacaopagar/<pk>', ClassificacaoPagarUpdateView.as_view(), name="atualiza_classificacao_pagar"),
    path('classificacaopagar/excluir/<pk>', ClassificacaoPagarDeleteView.as_view(), name="exclui_classificacao_pagar"),

    #Formas de pagamento
    path('formaspagamento/cadastrar/', FormasPagamentoCreateView.as_view(), name = "cria_formas_pagamento"),
    path('formaspagamento/', FormasPagamentoListView.as_view(), name="lista_formas_pagamento"),
    path('formaspagamento/<pk>', FormasPagamentoUpdateView.as_view(), name="atualiza_formas_pagamento"),
    path('formaspagamento/excluir/<pk>', FormasPagamentoDeleteView.as_view(), name="exclui_formas_pagamento"),

    #FLUXOS
    path('fluxo/', FluxoListView.as_view(), name = "fluxo"),   
    path('fluxomensal/', FluxoListView.as_view(), name = "fluxomensal")
]

website/forms.py
from django import forms
from bootstrap_datepicker_plus import DateTimePickerInput
from controlefinanceiro.models import ContasPagar, ContasReceber, ClassificacaoPagar, FormaPagamento

class InsereContasPagarForm(forms.ModelForm):         

    class Meta:
        model = ContasPagar

        fields = [           
            'data_vencimento',
            'data_pagamento',
            'valor',
            'descricao',
            'situacao',            
            'classificacoes',
            'formaspagamento'
        ]

        labels = {
            'data_vencimento': 'Data de Vencimento',
            'data_pagamento': 'Data de Pagamento ',
            'valor': 'Valor',
            'descricao': 'Descrição',
            'situacao': 'Situação',
            'classificacoes': 'Classificação',
            'formaspagamento': 'Forma de Pagamento'
        }

        widgets = {            
            'data_vencimento': DateTimePickerInput(format='%Y-%m-%d'), # specify date-frmat
            'data_pagamento': DateTimePickerInput(format='%Y-%m-%d'), # specify date-frmat
        }

class InsereContasReceberForm(forms.ModelForm):                        
    class Meta:
        model = ContasReceber
        fields = [
            'data_expectativa',
            'data_recebimento',
            'valor',
            'descricao',
            'situacao',
            'classificacoes',
            'formaspagamento' 
        ]
        labels = {
            'data_expectativa': 'Data de Expectativa de Recebimento',
            'data_recebimento': 'Data de Recebimento ',
            'valor': 'Valor',
            'descricao': 'Descrição',
            'situacao': 'Situação',
            'classificacoes': 'Classificação',
            'formaspagamento': 'Forma de Pagamento'
        }

        widgets = {            
            'data_expectativa': DateTimePickerInput(format='%Y-%m-%d'), # specify date-frmat
            'data_recebimento': DateTimePickerInput(format='%Y-%m-%d'), # specify date-frmat
        }

class InsereClassificaoPagarForm(forms.ModelForm):
    class Meta:
        model = ClassificacaoPagar
        fields = [
            'descricao',
            'tipo'
        ]

class InsereFormasPagamento(forms.ModelForm):
    class Meta:
        model = FormaPagamento
        fields = [
            'descricao'
        ]        

website/views.py
from django.views.generic import TemplateView, ListView, UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy
from django.db.models.functions import Cast
from django.db.models import Sum
from controlefinanceiro.models import ContasPagar, ContasReceber, ClassificacaoPagar, FormaPagamento
from website.forms import InsereContasPagarForm, InsereContasReceberForm, InsereClassificaoPagarForm, InsereFormasPagamento

# Create your views here.
class IndexTemplateView(TemplateView):
    template_name = "website/index.html"

#CONTAS A PAGAR ---------------------------------------------------------------    

class ContasPagarCreateView(CreateView):
    template_name = "website/contaspagar/criacontaspagar.html"
    model = ContasPagar
    form_class = InsereContasPagarForm
    success_url = reverse_lazy("website:lista_contas_pagar")

class ContasPagarListView(ListView):
    template_name = "website/contaspagar/listacontaspagar.html"
    model = ContasPagar    
    context_object_name = "contaspagar"
    
class ContasPagarUpdateView(UpdateView):
    template_name = "website/contaspagar/atualizacontaspagar.html"    
    model = ContasPagar
    fields = '__all__'
    context_objetc_name = "contaspagar"
    success_url = reverse_lazy("website:lista_contas_pagar")

class ContasPagarDeleteView(DeleteView):
    template_name = "website/contaspagar/excluicontaspagar.html"
    model = ContasPagar
    context_objetc_name = "contaspagar"
    success_url = reverse_lazy("website:lista_contas_pagar")

#CONTAS A RECEBER ---------------------------------------------------------------    

class ContasReceberCreateView(CreateView):
    template_name = "website/contasreceber/criacontasreceber.html"
    model = ContasReceber
    form_class = InsereContasReceberForm
    success_url = reverse_lazy("website:lista_contas_receber")

class ContasReceberListView(ListView):
    template_name = "website/contasreceber/listacontasreceber.html"
    model = ContasReceber
    context_object_name = "contasreceber"

class ContasReceberUpdateView(UpdateView):
    template_name = "website/contasreceber/atualizacontasreceber.html"    
    model = ContasReceber
    fields = '__all__'
    context_objetc_name = "contasreceber"
    success_url = reverse_lazy("website:lista_contas_receber")

class ContasReceberDeleteView(DeleteView):
    template_name = "website/contasreceber/excluicontasreceber.html"
    model = ContasReceber
    context_objetc_name = "contasreceber"
    success_url = reverse_lazy("website:lista_contas_receber")


#CLASSIFICAÇÃO DE CONTAS ---------------------------------------------------------------    

class ClassificacaoPagarCreateView(CreateView):
    template_name = "website/classificacaopagar/criaclassificacaopagar.html"
    model = ClassificacaoPagar
    form_class = InsereClassificaoPagarForm
    success_url = reverse_lazy("website:lista_classificacao_pagar")


class ClassificacaoPagarListView(ListView):
    template_name = "website/classificacaopagar/listaclassificacaopagar.html"
    model = ClassificacaoPagar
    context_object_name = "classificacaopagar"  
    
class ClassificacaoPagarUpdateView(UpdateView):
    template_name = "website/classificacaopagar/atualizaclassificacaopagar.html"    
    model = ClassificacaoPagar
    fields = '__all__'
    context_objetc_name = "classificacaopagar"
    success_url = reverse_lazy("website:lista_classificacao_pagar")

class ClassificacaoPagarDeleteView(DeleteView):
    template_name = "website/classificacaopagar/excluiclassificacaopagar.html"
    model = ClassificacaoPagar
    context_objetc_name = "classificacaopagar"
    success_url = reverse_lazy("website:lista_classificacao_pagar")   


#FORMAS DE PAGAMENTOS ---------------------------------------------------------------    
class FormasPagamentoListView(ListView):
    template_name = "website/formapagamento/listaformaspagamento.html"
    model = FormaPagamento
    context_object_name = "formapagamento"  

class FormasPagamentoCreateView(CreateView):
    template_name = "website/formapagamento/criaformaspagamento.html"
    model = FormaPagamento
    form_class = InsereFormasPagamento
    success_url = reverse_lazy("website:lista_formas_pagamento")

class FormasPagamentoUpdateView(UpdateView):
    template_name = "website/formapagamento/atualizaformaspagamento.html"    
    model = FormaPagamento
    fields = '__all__'
    context_objetc_name = "formapagamento"
    success_url = reverse_lazy("website:lista_formas_pagamento")

class FormasPagamentoDeleteView(DeleteView):
    template_name = "website/formapagamento/excluiformaspagamento.html"
    model = FormaPagamento
    context_objetc_name = "formapagamento"
    success_url = reverse_lazy("website:lista_formas_pagamento")   


class FluxoListView(ListView):
    template_name= "website/fluxo.html"

    context_object_name = "fluxo"       

    def get_queryset(self):
        return ContasPagar.objetos.order_by("data_vencimento").values('descricao', 'data_vencimento', 'data_pagamento', 'valor',
         'situacao')

    def get_context_data(self, **kwargs):
        context = super(FluxoListView, self).get_context_data(**kwargs  )
        context ['fluxoreceber']= {
            'fluxoreceber': ContasReceber.objetos.order_by("data_expectativa").values('descricao', 'data_expectativa',
                'data_recebimento', 'valor', 'situacao'), 
            'total_pagar': ContasPagar.objetos.all().filter(situacao = 'Pago').aggregate(Sum('valor')),
            'total_receber': ContasReceber.objetos.all().filter(situacao = 'Recebido').aggregate(Sum('valor'))
        }
        return context

    
    

website/templates/website/contaspagar/atualizacontaspagar.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Conta a Pagar{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar dados de conta a pagar</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Data de vencimento -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Data de Vencimento</span>
              </div>
              {% render_field form.data_vencimento class+="form-control" %}
            </div>

            <!-- Data de pagamento -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Data de Pagamento</span>
              </div>
              {% render_field form.data_pagamento class+="form-control" %}
            </div>

            <!-- Descrição -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Descrição</span>
              </div>
              {% render_field form.descricao class+="form-control" %}
            </div>

             <!-- Valor -->
             <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Valor</span>
              </div>
              {% render_field form.valor class+="form-control" %}
            </div>


            <!-- Situação -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Situação</span>
              </div>
              {% render_field form.situacao class+="form-control" %}
            </div>

            <!-- Classificação -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Classificação</span>
              </div>
              {% render_field form.classificacoes class+="form-control" %}
            </div>

            <!-- Forma de Pagamento -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Forma de Pagamento</span>
              </div>
              {% render_field form.formaspagamento class+="form-control" %}
            </div>

            <hr />
            <div class="text-right">
              <a href="{% url 'website:lista_contas_pagar' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/contaspagar/criacontaspagar.html
{% extends "website/_layouts/base.html" %}

{% load bootstrap4 %}
{% bootstrap_css %}  
{% bootstrap_javascript jquery='full' %}
{{ form.media }} 

{% block title %}Cadastro de contas a pagar{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastro de Conta a Pagar</h5>
          <p class="card-text">
            Complete o formulário abaixo para cadastrar
            uma nova <code>Conta</code>.
          </p>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}           

            {% bootstrap_form form %}

            <hr>
            <div class="text-right">
              <a href="{% url 'website:lista_contas_pagar' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/contaspagar/excluicontaspagar.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Exclusão de conta a pagar{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Conta a Pagar</h5>

        <p class="card-text">
          Você tem certeza que quer excluir a conta <b>{{ contaspagar.descricao }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'website:lista_contas_pagar' %}" class="btn btn-outline-danger">
              Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/website/contaspagar/listacontaspagar.html
{% extends "website/_layouts/base.html" %}

{% block title %}Lista de Contas a Pagar{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Contas a Pagar</h5>

          {% if contaspagar|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Contas a Pagar</code> cadastrados.
            </p>

            <table class="table">
              <thead class="thead-dark">
              <tr>               
                <th scope="col">Descrição</th>
                <th scope="col">Data de Vencimento</th>
                <th scope="col">Data de Pagamento</th>
                <th scope="col">Valor</th>
                <th scope="col">Situacao</th>
                <th scope="col">Classificação</th>
                <th scope="col">Forma de Pagamento</th>
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for conta in contaspagar %}
                <tr>
                  <th scope="row">{{ conta.descricao }}</th>
                  <td>{{ conta.data_vencimento|date:'d/m/Y' }}</td>
                  <td>{{ conta.data_pagamento|date:'d/m/Y' }}</td>
                  <td>{{ conta.valor }}</td>
                  <td>{{ conta.situacao }}</td>
                  <td>{{ conta.classificacoes.descricao }}</td>
                  <td>{{ conta.formaspagamento.descricao }}</td>
                  <td class="text-center">
                    <a href="{% url 'website:atualiza_contas_pagar' pk=conta.id %}"
                       class="btn btn-primary">
                      Atualizar
                    </a>
                    <a href="{% url 'website:exclui_contas_pagar' pk=conta.id %}"
                      class="btn btn-danger">
                        Excluir
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhuma <code>conta</code> cadastrada ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'website:cria_contas_pagar' %}" class="btn btn-primary">
              Cadastrar Conta
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}